<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="LAPTOP-JULIANPB" name="pytest" skipped="0" tests="6" time="8.864" timestamp="2022-05-26T16:01:52.057964"><testcase classname="tests.test_code" file="tests\test_code.py" line="4" name="test_version" time="0.005"></testcase><testcase classname="tests.test_model" file="tests\test_model.py" line="4" name="test_my_bag_of_words" time="0.003"></testcase><testcase classname="tests.test_model" file="tests\test_model.py" line="16" name="test_tfidf" time="0.019"></testcase><testcase classname="tests.test_preprocess" file="tests\test_preprocess.py" line="4" name="test_text_prepare" time="0.003"></testcase><testcase classname="tests.test_service" file="tests\test_service.py" line="8" name="test_predict" time="0.130"></testcase><testcase classname="tests.test_store" file="tests\test_store.py" line="7" name="test_store_load" time="0.011"><failure message="PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &apos;C:\\Users\\Jbies\\AppData\\Local\\Temp\\tmpush5ej9t&apos;">def test_store_load() -&gt; None:
        _, path = tempfile.mkstemp()
        data = {
            &quot;string&quot;: &quot;Hello there&quot;,
            &quot;int&quot;: 42,
            &quot;float&quot;: 3.141,
            &quot;tuple&quot;: (1, 2, 3, &quot;4&quot;),
            &quot;list&quot;: [1, 2, 3],
        }
        try:
            utils.store(data, path)
    
            loaded = utils.load(path)
    
            assert loaded == data  # nosec
        finally:
&gt;           os.remove(path)
E           PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: &apos;C:\\Users\\Jbies\\AppData\\Local\\Temp\\tmpush5ej9t&apos;

tests\test_store.py:24: PermissionError</failure></testcase></testsuite></testsuites>